In [35]:
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [3]:
X = pd.read_csv('gene_oneHotEncoding.csv', )
lineage = pd.read_csv('lineages.csv',sep='\t', index_col = 0)

In [4]:
X = X.set_index('Unnamed: 0')
X

group_1034  cysNC  group_1277  group_1352  group_1405  group_1784  \
Unnamed: 0                                                                      
2855                 0      1           1           1           1           1   
13685                0      1           1           1           1           1   
27228                0      0           1           1           1           1   
31457                0      1           1           1           1           1   
31458                0      1           1           1           1           1   
...                ...    ...         ...         ...         ...         ...   
61379                0      1           1           1           1           1   
61380                0      1           1           1           1           1   
61381                0      1           1           1           1           1   
61382                0      1           1           1           1           1   
61383                0      1           1           1           1           1   

            group_2013  group_2063  folP  group_340  ...  group_3840  \
Unnamed: 0                                           ...               
2855                 1           1     1          1  ...           0   
13685                1           1     1          1  ...           0   
27228                1           1     1          1  ...           0   
31457                1           1     1          1  ...           0   
31458                1           1     1          1  ...           0   
...                ...         ...   ...        ...  ...         ...   
61379                1           1     1          1  ...           1   
61380                1           1     1          1  ...           0   
61381                1           1     1          1  ...           0   
61382                1           1     1          1  ...           0   
61383                1           1     1          1  ...           0   

            group_3841  group_3842  group_3843  group_3844  group_3845  \
Unnamed: 0                                                               
2855                 0           0           0           0           0   
13685                0           0           0           0           0   
27228                0           0           0           0           0   
31457                0           0           0           0           0   
31458                0           0           0           0           0   
...                ...         ...         ...         ...         ...   
61379                1           1           0           0           0   
61380                0           0           1           0           0   
61381                0           0           0           0           0   
61382                0           0           0           1           1   
61383                0           0           0           0           0   

            group_3846  group_3847  group_3848  lineage  
Unnamed: 0                                               
2855                 0           0           0        1  
13685                0           0           0        1  
27228                0           0           0        1  
31457                0           0           0        1  
31458                0           0           0        1  
...                ...         ...         ...      ...  
61379                0           0           0        0  
61380                0           0           0        0  
61381                0           0           0        0  
61382                1           0           0        0  
61383                0           1           1        0  

[419 rows x 2453 columns]

In [5]:
lineage = lineage.set_index(X.index)


In [6]:
train, test = train_test_split(X, test_size = 0.2)
train.head()

group_1034  cysNC  group_1277  group_1352  group_1405  group_1784  \
Unnamed: 0                                                                      
31508                0      1           1           1           1           1   
31587                0      1           1           1           1           1   
31708                0      1           1           1           1           1   
31711                0      1           1           1           1           1   
31588                0      1           1           1           1           1   

            group_2013  group_2063  folP  group_340  ...  group_3840  \
Unnamed: 0                                           ...               
31508                1           1     1          1  ...           0   
31587                1           1     1          1  ...           0   
31708                1           1     1          1  ...           0   
31711                1           1     1          1  ...           0   
31588                1           1     1          1  ...           0   

            group_3841  group_3842  group_3843  group_3844  group_3845  \
Unnamed: 0                                                               
31508                0           0           0           0           0   
31587                0           0           0           0           0   
31708                0           0           0           0           0   
31711                0           0           0           0           0   
31588                0           0           0           0           0   

            group_3846  group_3847  group_3848  lineage  
Unnamed: 0                                               
31508                0           0           0        1  
31587                0           0           0        1  
31708                0           0           0        1  
31711                0           0           0        1  
31588                0           0           0        1  

[5 rows x 2453 columns]

In [7]:
X_train = train.iloc[:,:2452].to_numpy()
X_test = test.iloc[:,:2452].to_numpy()

In [8]:
y_train = train['lineage'].to_numpy()
y_test = test['lineage'].to_numpy()

In [9]:
#Train con variabili filtrate
ranked_data = pd.read_csv("geneRankedSVM.csv")
ranked_data = ranked_data.set_index('Unnamed: 0')
#ranked_f = ranked_data['0']

In [10]:
ranked_data

group_2306  fimA  group_2456  group_2383  group_453  group_95  \
Unnamed: 0                                                                  
2855                 0     0           0           1          0         1   
13685                0     1           0           0          0         1   
27228                1     0           0           1          1         1   
31457                0     0           0           1          0         1   
31458                0     1           0           0          0         1   
...                ...   ...         ...         ...        ...       ...   
61379                0     0           0           0          0         1   
61380                0     0           0           1          0         1   
61381                0     1           1           0          0         0   
61382                0     0           0           0          0         1   
61383                0     1           1           0          0         1   

            group_1503  rlmD  group_223  group_3517  ...  group_899  \
Unnamed: 0                                           ...              
2855                 0     0          0           0  ...          0   
13685                0     1          0           0  ...          0   
27228                0     1          0           0  ...          1   
31457                0     1          0           0  ...          0   
31458                1     1          0           0  ...          0   
...                ...   ...        ...         ...  ...        ...   
61379                0     1          0           0  ...          0   
61380                0     1          0           0  ...          0   
61381                0     1          0           0  ...          0   
61382                0     1          0           0  ...          0   
61383                0     1          0           0  ...          0   

            group_545  group_310  mafA1  group_1606  group_887  group_33  \
Unnamed: 0                                                                 
2855                1          0      1           0          0         0   
13685               1          1      1           0          1         0   
27228               1          0      1           0          1         1   
31457               1          1      1           0          0         1   
31458               1          1      1           0          1         1   
...               ...        ...    ...         ...        ...       ...   
61379               0          1      1           0          1         1   
61380               1          1      1           0          0         1   
61381               0          0      1           0          0         1   
61382               1          0      1           0          0         1   
61383               1          1      1           0          0         0   

            group_473  group_1644  group_2335  
Unnamed: 0                                     
2855                0           0           0  
13685               0           0           0  
27228               0           0           1  
31457               0           0           0  
31458               0           0           0  
...               ...         ...         ...  
61379               0           1           0  
61380               0           0           0  
61381               0           0           0  
61382               0           0           0  
61383               0           0           0  

[419 rows x 120 columns]

In [13]:
#n = 120

data_f = ranked_data.join(lineage)

lineage = lineage.set_index(data_f.index)

In [28]:
trainf, testf = train_test_split(data_f, test_size = 0.1)
X_trainf = trainf.iloc[:,:-1].to_numpy()
X_testf = testf.iloc[:,:-1].to_numpy()
y_trainf = trainf['lineage'].to_numpy()
y_testf = testf['lineage'].to_numpy()

In [39]:
#SVM
from sklearn import svm
svm = svm.SVC(kernel='linear')
svm.fit(X_trainf, y_trainf)
y_predf = svm.predict(X_testf)
metrics.confusion_matrix(y_testf, y_predf)

array([[ 8,  3],
       [ 0, 31]])

In [37]:
svm.score(X_testf, y_testf, sample_weight=None)

0.9285714285714286

In [40]:
#Cross Validation
from sklearn.model_selection import cross_val_score
Xf = data_f.iloc[:,:-1].to_numpy()
yf= data_f['lineage'].to_numpy()
scores = cross_val_score(svm, Xf, yf, cv=5)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.94 accuracy with a standard deviation of 0.03


In [18]:
lr.score(X_testf, y_testf, sample_weight=None)

0.8452380952380952

In [24]:
data_f.iloc[:,:-1]

group_2306  fimA  group_2456  group_2383  group_453  group_95  \
Unnamed: 0                                                                  
2855                 0     0           0           1          0         1   
13685                0     1           0           0          0         1   
27228                1     0           0           1          1         1   
31457                0     0           0           1          0         1   
31458                0     1           0           0          0         1   
...                ...   ...         ...         ...        ...       ...   
61379                0     0           0           0          0         1   
61380                0     0           0           1          0         1   
61381                0     1           1           0          0         0   
61382                0     0           0           0          0         1   
61383                0     1           1           0          0         1   

            group_1503  rlmD  group_223  group_3517  ...  group_899  \
Unnamed: 0                                           ...              
2855                 0     0          0           0  ...          0   
13685                0     1          0           0  ...          0   
27228                0     1          0           0  ...          1   
31457                0     1          0           0  ...          0   
31458                1     1          0           0  ...          0   
...                ...   ...        ...         ...  ...        ...   
61379                0     1          0           0  ...          0   
61380                0     1          0           0  ...          0   
61381                0     1          0           0  ...          0   
61382                0     1          0           0  ...          0   
61383                0     1          0           0  ...          0   

            group_545  group_310  mafA1  group_1606  group_887  group_33  \
Unnamed: 0                                                                 
2855                1          0      1           0          0         0   
13685               1          1      1           0          1         0   
27228               1          0      1           0          1         1   
31457               1          1      1           0          0         1   
31458               1          1      1           0          1         1   
...               ...        ...    ...         ...        ...       ...   
61379               0          1      1           0          1         1   
61380               1          1      1           0          0         1   
61381               0          0      1           0          0         1   
61382               1          0      1           0          0         1   
61383               1          1      1           0          0         0   

            group_473  group_1644  group_2335  
Unnamed: 0                                     
2855                0           0           0  
13685               0           0           0  
27228               0           0           1  
31457               0           0           0  
31458               0           0           0  
...               ...         ...         ...  
61379               0           1           0  
61380               0           0           0  
61381               0           0           0  
61382               0           0           0  
61383               0           0           0  

[419 rows x 120 columns]

In [32]:
#Cross Validation
from sklearn.model_selection import cross_val_score
Xf = data_f.iloc[:,:-1].to_numpy()
yf= data_f['lineage'].to_numpy()
scores = cross_val_score(LogisticRegression(penalty ='l2'), Xf, yf, cv=5)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.88 accuracy with a standard deviation of 0.06


In [22]:
scores

array([0.82142857, 0.91666667, 0.9047619 , 0.94047619, 0.79518072])

In [23]:
#normalizzazione
from sklearn import preprocessing
X_trainf_normalized = preprocessing.normalize(Xf, norm='l2')
scores = cross_val_score(LogisticRegression(penalty ='l2'), X_trainf_normalized, yf, cv=7)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


0.73 accuracy with a standard deviation of 0.05


In [32]:
scores

array([0.71666667, 0.73333333, 0.7       , 0.75      , 0.85      ,
       0.66666667, 0.71186441])

In [33]:
import mca

In [34]:
len(X.index)

419

In [35]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_trainf, y_trainf)
y_predf = rf.predict(X_testf)

In [36]:
rf.score(X_testf, y_testf, sample_weight=None)

0.8690476190476191

In [37]:
metrics.confusion_matrix(y_testf, y_predf)

array([[16, 10],
       [ 1, 57]])

In [38]:
#Cross Validation
from sklearn.model_selection import cross_val_score
Xf = data_f.iloc[:,:-1].to_numpy()
yf = data_f['lineage'].to_numpy()
X_trainf_normalized = preprocessing.normalize(Xf, norm='l2')
scores = cross_val_score(RandomForestClassifier(), X_trainf_normalized, yf, cv=7)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


0.72 accuracy with a standard deviation of 0.07


In [39]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

In [40]:
neigh = KNeighborsClassifier(n_neighbors=9)

In [41]:
neigh.fit(X_trainf, y_trainf)

KNeighborsClassifier(n_neighbors=9)

In [42]:
y_predf = neigh.predict(X_testf)
metrics.confusion_matrix(y_testf, y_predf)

array([[10, 16],
       [ 0, 58]])

In [43]:
neigh.score(X_testf, y_testf, sample_weight=None)

0.8095238095238095

In [44]:
#Cross Validation

X_trainf_normalized = preprocessing.normalize(Xf, norm='l2')
scores = cross_val_score(KNeighborsClassifier(n_neighbors=3), X_trainf_normalized, yf, cv=7)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.75 accuracy with a standard deviation of 0.10


In [45]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_trainf, y_trainf)
y_pred = gnb.predict(X_testf)

In [46]:
print("Number of mislabeled points out of a total %d points : %d"
  % (X_testf.shape[0], (y_testf != y_pred).sum()))

Number of mislabeled points out of a total 84 points : 18


In [47]:
metrics.confusion_matrix(y_testf, y_pred)

array([[10, 16],
       [ 2, 56]])

In [48]:
gnb.score(X_testf, y_testf, sample_weight=None)

0.7857142857142857